Коммит
EvgeniyN78/HomeWork_2.1.2_ObjectCar pull request #2
Opened 2022-12-03 06:37 UTC by EvgeniyN78

2022-12-05 06:30 UTC, OlgaLugacheva approved these changes

2022-12-10 12:47 UTC, EvgeniyN78 commented
Добрый день.
Делаю коммит "Автогонки".
Плохо получилось разобраться в теме. В теории всё понятно, на практике многое не получается.
Так и не смог исправить 1 ошибку в последнем задании: 
При объявлении метода печати водителей участвующих в гонке,  во вкладке "Main", "Java" просит сделать метод статичным. И далее статичным параметры Name в классе Driver. Из-за этого, к гонке допускается только один водитель не имеющих прав для управления другими транспортными средствами. Что делать с этим - не могу догадаться, т.ч. отправляю задание не законченным. Подскажите пожалуйста как это исправить.

2022-12-10 19:27 UTC, OlgaLugacheva requested changes

2022-12-10 19:27 UTC, OlgaLugacheva commented on src/Animals/Amphibians.java
> +package Animals;
пакет должен быть с маленькой буквы

2022-12-10 19:27 UTC, OlgaLugacheva commented on src/LicenseB.java
> +    public static String getStartMessage(PassengerCars passengerCars) {
нет , статик нужно убрать и в других классах аналогично

2022-12-10 19:27 UTC, OlgaLugacheva commented on src/Main.java
> +        System.out.println(LicenseB.getStartMessage(ford));
у нас же есть уже объекты лицензии с 110 по 121 строку
нужно убрать статик и вызывать этот метод у этих объектов 
вроде 

 System.out.println(ivanov.getStartMessage(yutong));

2022-12-11 06:53 UTC, EvgeniyN78 commented on src/Animals/Amphibians.java
> +package Animals;
Исправил. Спасибо огромное.

2022-12-11 06:53 UTC, EvgeniyN78 commented on src/LicenseB.java
> +    public static String getStartMessage(PassengerCars passengerCars) {
Исправил. Спасибо огромное.

2022-12-11 06:53 UTC, EvgeniyN78 commented on src/Main.java
> +        System.out.println(LicenseB.getStartMessage(ford));
Исправил. Спасибо огромное. Всё заработало.

2022-12-11 15:48 UTC, merged